# Generated by Django 4.2.4 on 2024-03-26 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='id',
        ),
        migrations.AlterField(
            model_name='register',
            name='logemail',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
