# Generated by Django 4.2.4 on 2024-03-26 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediapp', '0002_remove_register_id_alter_register_logemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='userid',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
