# Generated by Django 4.2.4 on 2024-03-29 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediapp', '0003_alter_login_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='password',
            new_name='logpass',
        ),
    ]
