# Generated by Django 4.2.4 on 2024-03-30 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediapp', '0004_rename_password_login_logpass'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletter',
            old_name='date',
            new_name='regdate',
        ),
    ]
