# Generated by Django 4.2.4 on 2024-05-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediapp', '0005_rename_date_newsletter_regdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clogin',
            fields=[
                ('userid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('psw', models.CharField(max_length=30)),
                ('usertype', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Cregister',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('phoneno', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=30)),
                ('highedu', models.CharField(max_length=50)),
                ('special', models.CharField(max_length=50)),
                ('work', models.CharField(max_length=10)),
                ('preorg', models.CharField(max_length=50)),
                ('regdate', models.CharField(max_length=30)),
            ],
        ),
    ]
