# Generated by Django 4.2.4 on 2024-06-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediapp', '0006_clogin_cregister'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anxtest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question1', models.CharField(max_length=40)),
                ('question2', models.CharField(max_length=50)),
                ('question3', models.CharField(max_length=40)),
                ('question4', models.CharField(max_length=40)),
                ('question5', models.CharField(max_length=50)),
                ('question6', models.CharField(max_length=40)),
            ],
        ),
    ]
